# Generated by Django 5.0.3 on 2024-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=1)),
                ('correct_answers', models.CharField(max_length=1)),
                ('question_number', models.IntegerField()),
                ('subject_contents', models.CharField(max_length=255)),
                ('assessment_areas', models.CharField(max_length=255)),
                ('sydney_correct_count_percentage', models.FloatField()),
                ('sydney_average_score', models.FloatField()),
                ('sydney_participants', models.IntegerField()),
                ('student_score', models.FloatField()),
                ('student_total_assessed', models.IntegerField()),
                ('student_area_assessed_score', models.FloatField()),
                ('total_area_assessed_score', models.FloatField()),
                ('participant', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.FloatField()),
                ('average_score', models.FloatField()),
                ('school_percentile', models.IntegerField()),
                ('sydney_percentile', models.IntegerField()),
                ('strength_status', models.CharField(max_length=1)),
                ('high_distinct_count', models.IntegerField()),
                ('distinct_count', models.IntegerField()),
                ('credit_count', models.IntegerField()),
                ('participant_count', models.IntegerField()),
                ('award', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='AssessmentArea',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
