# Generated by Django 5.0.6 on 2024-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('sydney_participants', models.IntegerField()),
                ('sydney_percentile', models.IntegerField()),
                ('assessment_area', models.CharField(max_length=255)),
                ('award', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correct_answer', models.BooleanField()),
                ('student_name', models.CharField(max_length=255)),
                ('student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('year_level_name', models.CharField(max_length=100)),
                ('answer_id', models.CharField(max_length=100)),
                ('correct_answer_id', models.CharField(max_length=100)),
            ],
        ),
    ]
